# Generated by Django 3.2.9 on 2021-12-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainchop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='for_anonymous_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pomp',
            name='throughput',
            field=models.CharField(max_length=10, verbose_name='Производительность, max (л/мин)'),
        ),
    ]
